name: Rust

on: [push, pull_request]

jobs:
  ubuntu-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rust stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cargo build 
        run: cargo build --workspace --all-targets --all-features
      - name: Cargo test
        run: cargo test --workspace --all-targets --all-features
      - name: Build libb
        run: ./target/debug/blang -s libb/lib.b -o libb/libb.a
      - name: Compiler test
        run: ./target/debug/comptest tests --verbose
  macos-aarch64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rust stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cargo build 
        run: cargo build --workspace --all-targets --all-features
      - name: Cargo test
        run: cargo test --workspace --all-targets --all-features
      - name: Build libb
        run: ./target/debug/blang -s libb/lib.b -o libb/libb.a
      - name: Compiler test
        run: ./target/debug/comptest tests --verbose
  windows-x86_64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rust stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cargo build 
        run: cargo build --workspace --all-targets --all-features
      - name: Cargo test
        run: cargo test --workspace --all-targets --all-features
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build libb
        run: .\target\debug\blang.exe -s libb\lib.b -o libb\libb.lib
      - name: Compiler test
        run: .\target\debug\comptest.exe tests --verbose
