name: Rust

on: [push, pull_request]

jobs:
  ubuntu-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rust stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cargo build 
        run: cargo build --workspace --all-targets --all-features
      - name: Cargo test
        run: cargo test --workspace --all-targets --all-features
      - name: Build libb
        run: make libb-x86_64-linux
      - name: Compiler test
        run: ./target/debug/comptest tests --verbose
  macos-aarch64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rust stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cargo build 
        run: cargo build --workspace --all-targets --all-features
      - name: Cargo test
        run: cargo test --workspace --all-targets --all-features
      - name: Build libb
        run: make libb-aarch64-darwin
      - name: Compiler test
        run: ./target/debug/comptest tests --verbose
